return {
    
    ["Southern San d'Oria"]       = { [1] = {unknown1=0},  [2] = {unknown1=1},   [3] = {unknown1=2},     [4] = {unknown1=97}},
    ["Northern San d'Oria"]       = { [1] = {unknown1=3},  [2] = {unknown1=4},   [3] = {unknown1=5},     [4] = {unknown1=98}},
    ["Port San d'Oria"]           = { [1] = {unknown1=6},  [2] = {unknown1=7},   [3] = {unknown1=8}},
    ["Bastok Mines"]              = { [1] = {unknown1=9},  [2] = {unknown1=10},  [3] = {unknown1=99}},
    ["Bastok Markets"]            = { [1] = {unknown1=11}, [2] = {unknown1=12},  [3] = {unknown1=13},    [4] = {unknown1=100}},
    ["Port Bastok"]               = { [1] = {unknown1=14}, [2] = {unknown1=15},  [3] = {unknown1=101}},
    ["Metalworks"]                = { [1] = {unknown1=16}, [2] = {unknown1=102}},
    ["Windurst Waters"]           = { [1] = {unknown1=17}, [2] = {unknown1=18},  [3] = {unknown1=103},   [4] = {unknown1=118}},
    ["Windurst Walls"]            = { [1] = {unknown1=19}, [2] = {unknown1=20},  [3] = {unknown1=21}},
    ["Port Windurst"]             = { [1] = {unknown1=22}, [2] = {unknown1=23},  [3] = {unknown1=24}},
    ["Windurst Woods"]            = { [1] = {unknown1=25}, [2] = {unknown1=26},  [3] = {unknown1=27},    [4] = {unknown1=28},    [5] = {unknown1=119}},
    ["Ru'Lude Gardens"]           = { [1] = {unknown1=29}, [2] = {unknown1=30},  [3] = {unknown1=31}},
    ["Upper Jeuno"]               = { [1] = {unknown1=32}, [2] = {unknown1=33},  [3] = {unknown1=34}},
    ["Lower Jeuno"]               = { [1] = {unknown1=35}, [2] = {unknown1=36}},
    ["Port Jeuno"]                = { [1] = {unknown1=37}, [2] = {unknown1=38}},
    ["Kazham"]                    = { [1] = {unknown1=39}},
    ["Mhaura"]                    = { [1] = {unknown1=40}},
    ["Norg"]                      = { [1] = {unknown1=41}, [2] = {unknown1=104}},
    ["Rabao"]                     = { [1] = {unknown1=42}, [2] = {unknown1=105}},
    ["Selbina"]                   = { [1] = {unknown1=43}},
    ["Western Adoulin"]           = { [1] = {unknown1=44}, [2] = {unknown1=109}},
    ["Eastern Adoulin"]           = { [1] = {unknown1=45}, [2] = {unknown1=110}},
    ["Ceizak Battlegrounds"]      = { [1] = {unknown1=46}},
    ["Foret de Hennetiel"]        = { [1] = {unknown1=47}},
    ["Morimar Basalt Fields"]     = { [1] = {unknown1=48}},
    ["Yorcia Weald"]              = { [1] = {unknown1=49}},
    ["Marjami Ravine"]            = { [1] = {unknown1=50}},
    ["Kamihr Drifts"]             = { [1] = {unknown1=51}},
    ["Yughott Grotto"]            = { [1] = {unknown1=52}},
    ["Palborough Mines"]          = { [1] = {unknown1=53}},
    ["Giddeus"]                   = { [1] = {unknown1=54}},
    ["Fei'Yin"]                   = { [1] = {unknown1=55}, [2] = {unknown1=94}},
    ["Quicksand Caves"]           = { [1] = {unknown1=56}, [2] = {unknown1=96}},
    ["Den of Rancor"]             = { [1] = {unknown1=57}, [2] = {unknown1=93}},
    ["Castle Zvahl Keep"]         = { [1] = {unknown1=58}},
    ["Ru'Aun Gardens"]            = { [1] = {unknown1=59}, [2] = {unknown1=60},  [3] = {unknown1=61},    [4] = {unknown1=62},    [5] = {unknown1=63}},
    ["Tavnazian Safehold"]        = { [1] = {unknown1=64}, [2] = {unknown1=120}, [3] = {unknown1=121}},
    ["Aht Urhgan Whitegate"]      = { [1] = {unknown1=65}, [2] = {unknown1=106}, [3] = {unknown1=107},   [4] = {unknown1=108}},
    ["Nashmau"]                   = { [1] = {unknown1=66}},
    ["Al Zahbi"]                  = { [1] = {unknown1=67}},
    ["Southern San d'Oria [S]"]   = { [1] = {unknown1=68}},
    ["Bastok Markets [S]"]        = { [1] = {unknown1=69}},
    ["Windurst Waters [S]"]       = { [1] = {unknown1=70}},
    ["Upper Delkfutt's Tower"]    = { [1] = {unknown1=71}},
    ["The Shrine of Ru'Avitau"]   = { [1] = {unknown1=72}},
    ["Riverne - Site #B01"]       = { [1] = {unknown1=73}},
    ["Bhaflau Thickets"]          = { [1] = {unknown1=74}},
    ["Caedarva Mire"]             = { [1] = {unknown1=75}},
    ["Uleguerand Range"]          = { [1] = {unknown1=76}, [2] = {unknown1=77},  [3] = {unknown1=78},    [4] = {unknown1=79},    [5] = {unknown1=80}},
    ["Attohwa Chasm"]             = { [1] = {unknown1=81}},
    ["Pso'Xja"]                   = { [1] = {unknown1=82}},
    ["Newton Movalpolos"]         = { [1] = {unknown1=83}},
    ["Riverne - Site #A01"]       = { [1] = {unknown1=84}},
    ["Al'Taieu"]                  = { [1] = {unknown1=85}, [2] = {unknown1=86},  [3] = {unknown1=87}},
    ["Grand Palace of Hu'Xzoi"]   = { [1] = {unknown1=88}},
    ["The Garden of Ru'Hmet"]     = { [1] = {unknown1=89}},
    ["Mount Zhayolm"]             = { [1] = {unknown1=90}},
    ["Cape Teriggan"]             = { [1] = {unknown1=91}},
    ["The Boyahda Tree"]          = { [1] = {unknown1=92}},
    ["Ifrit's Cauldron"]          = { [1] = {unknown1=95}},
    ["Xarcabard [S]"]             = { [1] = {unknown1=111}},
    ["Leafallia"]                 = { [1] = {unknown1=112}},
    ["Castle Zvahl Keep [S]"]     = { [1] = {unknown1=113}},
    ["Qufim Island"]              = { [1] = {unknown1=114}},
    ["Toraimarai Canal"]          = { [1] = {unknown1=115}},
    ["Ra'Kaznar Inner Court"]     = { [1] = {unknown1=116}},
    ["Misareaux Coast"]           = { [1] = {unknown1=117}},

}