return {
    
    ["Ru'Lude Gardens"]       = {  option=4  },
    ["Selbina"]               = {  option=5  },
    ["Mhaura"]                = {  option=6  },
    ["Rabao"]                 = {  option=7  },
    ["Norg"]                  = {  option=8  },
    ["West Ronfaure"]         = {  option=9  },
    ["North Gustaberg"]       = {  option=10 },
    ["West Sarutabaruta"]     = {  option=11 },
    ["La Theine Plateau"]     = {  option=12 },
    ["Konschtat Highlands"]   = {  option=13 },
    ["Tahrongi Canyon"]       = {  option=14 },
    ["Jugner Forest"]         = {  option=15 },
    ["Pashhow Marshlands"]    = {  option=16 },
    ["Meriphataud Mountains"] = {  option=17 },
    ["Attohwa Chasm"]         = {  option=18 },
    ["Uleguerand Range"]      = {  option=19 },
    ["Davoi"]                 = {  option=20 },
    ["Beadeaux"]              = {  option=21 },
    ["Castle Oztroja"]        = {  option=22 },
    ["Quicksand Caves"]       = {  option=23 },
    ["Sea Serpent Grotto"]    = {  option=24 },
    ["Temple of Uggalepih"]   = {  option=25 },
    ["The Boyahda Tree"]      = {  option=26 },
    ["Oldton Movalpolos"]     = {  option=27 },
    ["Riverne - Site B01"]    = {  option=28 },
    ["Castle Zvahl Keep"]     = {  option=29 },
    
}