return {
        
    ["Northern San d'Oria"]         = {  [1] = {option=0}   },
    ["Bastok Mines"]                = {  [1] = {option=1}   },
    ["Port Windurst"]               = {  [1] = {option=2}   },
    ["Ru'Lude Gardens"]             = {  [1] = {option=3}   },
    ["Tavnazian Safehold"]          = {  [1] = {option=4}   },
    ["Aht Urhgan Whitegate"]        = {  [1] = {option=5}   },
    ["West Ronfaure"]               = {  [1] = {option=6}   },
    ["Fort Ghelsba"]                = {  [1] = {option=7}   },
    ["Bostaunieux Oubliette"]       = {  [1] = {option=8}   },
    ["King Ranperre's Tomb"]        = {  [1] = {option=9}   },
    ["La Theine Plateau"]           = {  [1] = {option=10}  },
    ["Valkurm Dunes"]               = {  [1] = {option=11}  },
    ["Konschtat Highlands"]         = {  [1] = {option=12}  },
    ["Ordelle's Caves"]             = {  [1] = {option=13}  },
    ["Gusgen Mines"]                = {  [1] = {option=14}  },
    ["Carpenters' Landing"]         = {  [1] = {option=15}  },
    ["Jugner Forest"]               = {  [1] = {option=16}  },
    ["Batallia Downs"]              = {  [1] = {option=17}  },
    ["Davoi"]                       = {  [1] = {option=18}  },
    ["The Eldieme Necropolis"]      = {  [1] = {option=19}  },
    ["North Gustaberg"]             = {  [1] = {option=20}  },
    ["Zeruhn Mines"]                = {  [1] = {option=21}  },
    ["Korroloka Tunnel"]            = {  [1] = {option=22}  },
    ["Dangruf Wadi"]                = {  [1] = {option=23}  },
    ["Pashhow Marshlands"]          = {  [1] = {option=24}  },
    ["Rolanberry Fields"]           = {  [1] = {option=25}  },
    ["Beadeaux"]                    = {  [1] = {option=26}  },
    ["Crawlers' Nest"]              = {  [1] = {option=27}  },
    ["West Sarutabaruta"]           = {  [1] = {option=28}  },
    ["Toraimarai Canal"]            = {  [1] = {option=29}  },
    ["Horutoto Ruins"]              = {  [1] = {option=30}  },
    ["Bibiki Bay"]                  = {  [1] = {option=31}  },
    ["Tahrongi Canyon"]             = {  [1] = {option=32}  },
    ["Buburimu Peninsula"]          = {  [1] = {option=33}  },
    ["Maze of Shakhrami"]           = {  [1] = {option=34}  },
    ["Labyrinth of Onzozo"]         = {  [1] = {option=35}  },
    ["Meriphataud Mountains"]       = {  [1] = {option=36}  },
    ["Sauromugue Champaign"]        = {  [1] = {option=37}  },
    ["Castle Oztroja"]              = {  [1] = {option=38}  },
    ["Garlaige Citadel"]            = {  [1] = {option=39}  },
    ["Beaucedine Glacier"]          = {  [1] = {option=40}  },
    ["Ranguemont Pass"]             = {  [1] = {option=41}  },
    ["Xarcabard"]                   = {  [1] = {option=42}  },
    ["Castle Zvahl Baileys"]        = {  [1] = {option=43}  },
    ["Qufim Island"]                = {  [1] = {option=44}  },
    ["Behemoth's Dominion"]         = {  [1] = {option=45}  },
    ["Lower Delkfutt's Tower"]      = {  [1] = {option=46}  },
    ["The Sanctuary of Zi'Tah"]     = {  [1] = {option=47}  },
    ["Ro'Maeve"]                    = {  [1] = {option=48}  },
    ["Dragon's Aery"]               = {  [1] = {option=49}  },
    ["Eastern Altepa Desert"]       = {  [1] = {option=50}  },
    ["Western Altepa Desert"]       = {  [1] = {option=51}  },
    ["Rabao"]                       = {  [1] = {option=52}  },
    ["Cape Teriggan"]               = {  [1] = {option=53}  },
    ["Valley of Sorrows"]           = {  [1] = {option=54}  },
    ["Kuftal Tunnel"]               = {  [1] = {option=55}  },
    ["Gustav Tunnel"]               = {  [1] = {option=56}  },
    ["Yuhtunga Jungle"]             = {  [1] = {option=57}  },
    ["Sea Serpent Grotto"]          = {  [1] = {option=58}  },
    ["Kazham"]                      = {  [1] = {option=59}  },
    ["Norg"]                        = {  [1] = {option=60}  },
    ["Yhoator Jungle"]              = {  [1] = {option=61}  },
    ["Temple of Uggalepih"]         = {  [1] = {option=62}  },
    ["Ifrit's Cauldron"]            = {  [1] = {option=63}  },
    ["Ru'Aun Gardens"]              = {  [1] = {option=64}  },
    ["Oldton Movalpolos"]           = {  [1] = {option=65}  },
    ["Lufaise Meadows"]             = {  [1] = {option=66}  },
    ["Misareaux Coast"]             = {  [1] = {option=67}  },
    ["Phomiuna Aqueducts"]          = {  [1] = {option=68}  },
    ["Sacrarium"]                   = {  [1] = {option=69}  },
    ["Wajaom Woodlands"]            = {  [1] = {option=70}  },
    ["Mamook"]                      = {  [1] = {option=71}  },
    ["Aydeewa Subterrane"]          = {  [1] = {option=72}  },
    ["Halvung"]                     = {  [1] = {option=73}  },
    ["Nashmau"]                     = {  [1] = {option=74}  },
    ["Arrapago Reef"]               = {  [1] = {option=75}  },
    ["Caedarva Mire"]               = {  [1] = {option=76}  },
    ["Southern San d'Oria [S]"]     = {  [1] = {option=77}  },
    ["East Ronfaure [S]"]           = {  [1] = {option=78}  },
    ["Jugner Forest [S]"]           = {  [1] = {option=79}  },
    ["Batallia Downs [S]"]          = {  [1] = {option=80}  },
    ["The Eldieme Necropolis [S]"]  = {  [1] = {option=81}  },
    ["Bastok Markets [S]"]          = {  [1] = {option=82}  },
    ["North Gustaberg [S]"]         = {  [1] = {option=83}  },
    ["Grauberg [S]"]                = {  [1] = {option=84}  },
    ["Vunkerl Inlet [S]"]           = {  [1] = {option=85}  },
    ["Pashhow Marshlands [S]"]      = {  [1] = {option=86}  },
    ["Rolanberry Fields [S]"]       = {  [1] = {option=87}  },
    ["Crawlers' Nest [S]"]          = {  [1] = {option=88}  },
    ["Windurst Waters [S]"]         = {  [1] = {option=89}  },
    ["West Sarutabaruta [S]"]       = {  [1] = {option=90}  },
    ["Fort Karugo-Narugo [S]"]      = {  [1] = {option=91}  },
    ["Meriphataud Mountains [S]"]   = {  [1] = {option=92}  },
    ["Sauromugue Champaign [S]"]    = {  [1] = {option=93}  },
    ["Garlaige Citadel [S]"]        = {  [1] = {option=94}  },
    ["Beaucedine Glacier [S]"]      = {  [1] = {option=95}  },
    ["Castle Zvahl Baileys [S]"]    = {  [1] = {option=96}  },
    ["Eastern Adoulin"]             = {  [1] = {option=97}  },
    
}