return {
        
    ["East Ronfaure"]               = {  [1] = {option=0001}  },
	["South Gustaberg"]             = {  [1] = {option=0033}  },
	["East Sarutabaruta"]           = {  [1] = {option=0065}  },
	["La Theine Plateau"]           = {  [1] = {option=0097}  },
	["Konschtat Highlands"]         = {  [1] = {option=0129}  },
	["Tahrongi Canyon"]             = {  [1] = {option=0161}  },
	["Valkurm Dunes"]               = {  [1] = {option=0193}  },
	["Buburimu Peninsula"]          = {  [1] = {option=0225}  },
	["Qufim Island"]                = {  [1] = {option=0257}  },
	["Bibiki Bay"]                  = {  [1] = {option=0289}  },
	["Carpenters' Landing"]         = {  [1] = {option=0321}  },
	["Yuhtunga Jungle"]             = {  [1] = {option=0353}  },
	["Lufaise Meadows"]             = {  [1] = {option=0385}  },
	["Jugner Forest"]               = {  [1] = {option=0417}  },
	["Pashhow Marshlands"]          = {  [1] = {option=0449}  },
	["Meriphataud Mountains"]       = {  [1] = {option=0481}  },
	["Eastern Altepa Desert"]       = {  [1] = {option=0513}  },
	["Yhoator Jungle"]              = {  [1] = {option=0545}  },
	["The Sanctuary of Zi'Tah"]     = {  [1] = {option=0577}  },
	["Misareaux Coast"]             = {  [1] = {option=0609}  },
	["Labyrinth of Onzozo"]         = {  [1] = {option=0641}  },
	["Bostaunieux Oubliette"]       = {  [1] = {option=0673}  },
	["Batallia Downs"]              = {  [1] = {option=0705}  },
	["Rolanberry Fields"]           = {  [1] = {option=0737}  },
	["Sauromugue Champaign"]        = {  [1] = {option=0769}  },
	["Beaucedine Glacier"]          = {  [1] = {option=0801}  },
	["Xarcabard"]                   = {  [1] = {option=0833}  },
	["Ro'Maeve"]                    = {  [1] = {option=0865}  },
	["Western Altepa Desert"]       = {  [1] = {option=0897}  },
	["Attohwa Chasm"]               = {  [1] = {option=0929}  },
	["Garlaige Citadel"]            = {  [1] = {option=0961}  },
	["Ifrit's Cauldron"]            = {  [1] = {option=0993}  },
	["The Boyahda Tree"]            = {  [1] = {option=1025}  },
	["Kuftal Tunnel"]               = {  [1] = {option=1057}  },
	["Sea Serpent Grotto"]          = {  [1] = {option=1089}  },
	["Temple of Uggalepih"]         = {  [1] = {option=1121}  },
	["Quicksand Caves"]             = {  [1] = {option=1153}  },
	["Wajaom Woodlands"]            = {  [1] = {option=1185}  },
	["Lufaise Meadows"]             = {  [1] = {option=1217}  },
	["Cape Teriggan"]               = {  [1] = {option=1249}  },
	["Uleguerand Range"]            = {  [1] = {option=1313}  },
	["Den of Rancor"]               = {  [1] = {option=1345}  },
	["Fei'Yin"]                     = {  [1] = {option=1377}  },
	["Alzadaal Undersea Ruins"]     = {  [1] = {option=1441}  },
	--["Misareaux Coast"]           = {  [1] = {option=1473}  },
	["Mount Zhayolm"]               = {  [1] = {option=1505}  },
	["Gustav Tunnel"]               = {  [1] = {option=1537}  },
	["Behemoth's Dominion"]         = {  [1] = {option=1569}  },
	--["The Boyahda Tree"]          = {  [1] = {option=1601}  },
	["Valley of Sorrows"]           = {  [1] = {option=1633}  },
	--["Wajaom Woodlands"]          = {  [1] = {option=1665}  },
	--["Mount Zhayolm"]             = {  [1] = {option=1697}  },
	["Caedarva Mire"]               = {  [1] = {option=1729}  },
	["Aydeewa Subterrane"]          = {  [1] = {option=1761}  },
    
}