return {
        
    ["East Ronfaure"]               = {  [1] = {option=01}  },
    ["East Ronfaure [S]"]           = {  [1] = {option=02}  },
    ["Ordelle's Caves"]             = {  [1] = {option=03}  },
    ["Jugner Forest"]               = {  [1] = {option=04}  },
    ["Jugner Forest [S]"]           = {  [1] = {option=05}  },
    ["King Ranperre's Tomb"]        = {  [1] = {option=06}  },
    
    ["North Gustaberg"]             = {  [1] = {option=07}  },
    ["North Gustaberg [S]"]         = {  [1] = {option=08}  },
    ["Gusgen Mines"]                = {  [1] = {option=09}  },
    ["Pashhow Marshlands"]          = {  [1] = {option=10}  },
    ["Pashhow Marshlands [S]"]      = {  [1] = {option=11}  },
    ["Dangruf Wadi"]                = {  [1] = {option=12}  },
    
    ["West Sarutabaruta"]           = {  [1] = {option=13}  },
    ["West Sarutabaruta [S]"]       = {  [1] = {option=14}  },
    ["Maze of Shakrami"]            = {  [1] = {option=15}  },
    ["Meriphataud Mountains"]       = {  [1] = {option=16}  },
    ["Meriphataud Mountains [S]"]   = {  [1] = {option=17}  },
    ["Outer Horutoto Ruins"]        = {  [1] = {option=18}  },
    
    ["Batallia Downs"]              = {  [1] = {option=19}  },
    ["Batallia Downs [S]"]          = {  [1] = {option=20}  },
    ["Rolanberry Fields"]           = {  [1] = {option=21}  },
    ["Rolanberry Fields [S]"]       = {  [1] = {option=22}  },
    ["Sauromugue Champaign"]        = {  [1] = {option=23}  },
    ["Sauromugue Champaign [S]"]    = {  [1] = {option=24}  },
    ["The Eldieme Necropolis"]      = {  [1] = {option=25}  },
    ["The Eldieme Necropolis [S]"]  = {  [1] = {option=26}  },
    ["Crawlers' Nest"]              = {  [1] = {option=27}  },
    ["Crawlers' Nest [S]"]          = {  [1] = {option=28}  },
    ["Garliage Citadel"]            = {  [1] = {option=29}  },
    ["Garliage Citadel [S]"]        = {  [1] = {option=30}  },
    ["Qufim Island"]                = {  [1] = {option=31}  },
    ["Lower Delkfutt's Tower"]      = {  [1] = {option=32}  },
    ["Behemoth's Dominion"]         = {  [1] = {option=33}  },
    
    -- Jeuno II
    ["West Ronfaure"]               = {  [1] = {option=46}  },
    ["South Gustaberg"]             = {  [1] = {option=47}  },
    ["East Sarutabaruta"]           = {  [1] = {option=48}  },
    ["La Theine Plateau"]           = {  [1] = {option=49}  },
    ["Konschtat Highlands"]         = {  [1] = {option=50}  },
    ["Tahrongi Canyon"]             = {  [1] = {option=51}  },
    ["Vunkerl Inlet [S]"]           = {  [1] = {option=52}  },
    ["Grauberg [S]"]                = {  [1] = {option=53}  },
    ["Fort Karugo-Narugo [S]"]      = {  [1] = {option=54}  },
    ["Valkurm Dunes"]               = {  [1] = {option=55}  },
    ["Buburimu Peninsula"]          = {  [1] = {option=56}  },
    
    ["Yuhtunga Jungle"]             = {  [1] = {option=34}  },
    ["Temple of Uggalepih"]         = {  [1] = {option=35}  },
    ["Ifrit's Cauldron"]            = {  [1] = {option=36}  },
    ["Western Altepa Desert"]       = {  [1] = {option=37}  },
    ["Quicksand Caves"]             = {  [1] = {option=38}  },
    ["Kuftal Tunnel"]               = {  [1] = {option=39}  },
    ["The Sanctuary of Zi'Tah"]     = {  [1] = {option=40}  },
    ["The Boyahda Tree"]            = {  [1] = {option=41}  },
    ["Ro'Maeve"]                    = {  [1] = {option=42}  },
    ["Ru'Aun Gardens"]              = {  [1] = {option=43}  },
    ["The Shrine of Ru'Avitau"]     = {  [1] = {option=44}  },
    ["Ve'Lugannon Palace"]          = {  [1] = {option=45}  },
    
    ["Attohwa Chasm"]               = {  [1] = {option=57}  },
    ["Lufaise Meadows"]             = {  [1] = {option=58}  },
    ["Misareaux Coast"]             = {  [1] = {option=59}  },
    ["Uleguerand Range"]            = {  [1] = {option=60}  },
    ["Bibiki Bay"]                  = {  [1] = {option=61}  },
    
    ["Arrapago Reef"]               = {  [1] = {option=62}  },
    ["Caedarva Mire"]               = {  [1] = {option=63}  },
    ["Mamook"]                      = {  [1] = {option=64}  },
    ["Mount Zhayolm"]               = {  [1] = {option=65}  },
    ["Aydeewa Subterrane"]          = {  [1] = {option=66}  },
    
}