return {
["East Ronfaure"] = {[1] = {option=1},
["East Ronfaure [S]"] = {[1] = {option=2},
["LaTheine Plateau"] = {[1] = {option=3},
["Jugner Forest"] = {[1] = {option=4},
["Jugner Forest [S]"] = {[1] = {option=5},
["East Ronfaure"] = {[1] = {option=6},
["North Gustaberg"] = {[1] = {option=7},
["North Gustaberg [S]"] = {[1] = {option=8},
["Konschtat Highlands"] = {[1] = {option=9},
["Pashhow Marshlands"] = {[1] = {option=10},
["Pashhow Marshlands [S]"] = {[1] = {option=11},
["South Gustaberg"] = {[1] = {option=12},
["West Sarutabaruta"] = {[1] = {option=13},
["West Sarutabaruta [S]"] = {[1] = {option=14},
["Tahrongi Canyon"] = {[1] = {option=15},
["Meriphataud Mountains"] = {[1] = {option=16},
["Meriphataud Mountains [S]"] = {[1] = {option=17},
["West Sarutabaruta"] = {[1] = {option=18},
["Batallia Downs"] = {[1] = {option=19},
["Batallia Downs [S]"] = {[1] = {option=20},
["Rolanberry Fields"] = {[1] = {option=21},
["Rolanberry Fields [S]"] = {[1] = {option=22},
["Sauromugue Champaign"] = {[1] = {option=23},
["Sauromugue Champaign [S]"] = {[1] = {option=24},
["Batallia Downs"] = {[1] = {option=25},
["Batallia Downs [S]"] = {[1] = {option=26},
["Rolanberry Fields"] = {[1] = {option=27},
["Rolanberry Fields [S]"] = {[1] = {option=28},
["Sauromugue Champaign"] = {[1] = {option=29},
["Sauromugue Champaign [S]"] = {[1] = {option=30},
["Qufim Island"] = {[1] = {option=31},
["Delkfut's Tower"] = {[1] = {option=32},
["Behemoth's Dominion"] = {[1] = {option=33},
["Yuhtunga Jungle"] = {[1] = {option=34},
["Ifrit's Culdron"] = {[1] = {option=35},
["Temple of Uggalepih"] = {[1] = {option=36},
["Western Altepa Desert"] = {[1] = {option=37},
["Quicksand Caves"] = {[1] = {option=38},
["Kuftal Tunnel"] = {[1] = {option=39},
["The Sanctuary of Zi'Tah"] = {[1] = {option=40},
["The Boyahda Tree"] = {[1] = {option=41},
["Ro'Maeve"] = {[1] = {option=42},
["Hall of the Gods"] = {[1] = {option=43},
["West Ronfaure"] = {[1] = {option=44},
["South Gustaberg"] = {[1] = {option=45},
["East Sarutabaruta"] = {[1] = {option=46},
["La Theine Plateau"] = {[1] = {option=47},
["Konschtat Highlands"] = {[1] = {option=48},
["Tahrongi Canyon"] = {[1] = {option=49},
["Vunkerl Inlet [S]"] = {[1] = {option=50},
["Grauberg [S]"] = {[1] = {option=51},
["Fort Karugo-Narugo [S]"] = {[1] = {option=52},
["Valkurm Dunes"] = {[1] = {option=53},
["Buburimu Peninsula"] = {[1] = {option=54},
["Beaucedine Glacier"] = {[1] = {option=55},
["Lufaise Meadows"] = {[1] = {option=56},
["Misareaux Coast"] = {[1] = {option=57},
["Uleguerand Range"] = {[1] = {option=58},
["Attohwa Chasm"] = {[1] = {option=59},
["Bibiki Bay"] = {[1] = {option=60},
["Caedarva Mire"] = {[1] = {option=61},
["Mount Zhayolm"] = {[1] = {option=62},
["Wajaom Woodlands"] = {[1] = {option=63},
["Caedarva Mire"] = {[1] = {option=64},
["Bhaflau Thickets"] = {[1] = {option=65},

}
