return {
    [0] = "A Moogle Kupo d'Etat",
    [1] = 'Drenched! It Began with a Raindrop',
    [2] = 'Hasten! In a Jam in Jeuno?',
    [3] = 'Welcome! To My Decrepit Domicile',
    [4] = 'Curses! A Horrifically Harrowing Hex',
    [5] = "An Errand! The Professor's Price",
    [6] = 'Shock! Arrant Abuse of Authority',
    [7] = 'Lender Beware! Read the Fine Print',
    [8] = "Rescue! A Moogle's Labor of Love",
    [9] = 'Roar! A Cat Burglar Bares Her Fangs',
    [10] = 'Relief! A Triumphant Return',
    [11] = 'Joy! Summoned to a Fabulous Fete',
    [12] = 'A Challenge! You Could Be a Winner',
    [13] = 'Smash! A Malevolent Menace',
    [14] = "A Moogle Kupo d'Etat (Fin.)",
}
