return {
    [0] = 'A Shantotto Ascension',
    [1] = 'Burgeoning Dread',
    [2] = 'That Which Curdles Blood',
    [3] = 'Sugar-coated Directive',
    [4] = 'Enemy of the Empire (I)',
    [5] = 'Enemy of the Empire (II)',
    [6] = 'Sugar-coated Subterfuge',
    [7] = 'Shantotto in Chains',
    [8] = 'Fountain of Trouble',
    [9] = 'Battaru Royale',
    [10] = 'Romancing the Clone',
    [11] = 'Sisters in Arms',
    [12] = 'Project: Shantottofication',
    [13] = 'An Uneasy Peace',
    [14] = 'A Shantotto Ascension (Fin)',
}
