return {
    [0] = 'Smash the Orcish Scouts',
    [1] = 'Bat Hunt',
    [2] = 'Save the Children',
    [3] = 'The Rescue Drill',
    [4] = 'The Davoi Report',
    [5] = 'Journey Abroad',
    [6] = 'Journey to Bastok',
    [7] = 'Journey to Windurst',
    [8] = 'Journey to Bastok',
    [9] = 'Journey to Windurst',
    [10] = 'Infiltrate Davoi',
    [11] = 'The Crystal Spring',
    [12] = 'Appointment to Jeuno',
    [13] = 'Magicite',
    [14] = "The Ruins of Fei'Yin",
    [15] = 'The Shadow Lord',
    [16] = "Leaute's Last Wishes",
    [17] = "Ranperre's Final Rest",
    [18] = 'Prestige of the Papsque',
    [19] = 'The Secret Weapon',
    [20] = 'Coming of Age',
    [21] = 'Lightbringer',
    [22] = 'Breaking Barriers',
    [23] = 'The Heir to the Light',
}
